[package]
name = "hex"
version = "1.0.2"
description = "Convert between Nat8 values/arrays and hexadecimal string representation"
repository = "https://github.com/f0i/hex"
keywords = [ "hex", "encoding", "decoding", "utils", "bytes" ]
license = "MIT"

[dependencies]
core = "1.0.0"

[toolchain]
moc = "0.16.2"
